# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0002_tournament_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rivals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('teamA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rival_A', to='elo.Team')),
                ('teamB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rival_B', to='elo.Team')),
            ],
        ),
    ]
