# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0003_rivals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rivals',
            old_name='teamA',
            new_name='team_a',
        ),
        migrations.RenameField(
            model_name='rivals',
            old_name='teamB',
            new_name='team_b',
        ),
    ]
