# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0004_auto_20170330_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentRankingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1500)),
                ('date', models.DateTimeField()),
                ('position', models.IntegerField()),
                ('change', models.TextField(max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elo.Team')),
            ],
        ),
    ]
